### ISSUE TITLE
We loose one character for it to come in check Digit

### ISSUE THREAD

**Issue by gtmsingh** [chilts/node-coupon-code#8] opened 2016-10-05 07:17 UTC
In the following function :
```
function checkDigitAlg1(data, check) {
    // check's initial value is the part number (e.g. 3 or above)

    // loop through the data chars
    data.split('').forEach(function(v) {
        var k = symbolsObj[v];
        check = check * 19 + k;
    });

    return symbolsArr[ check % 31 ];
}
```
When the symbol is returned, it should be **symbolsArr[ check % _32_ ];** instead of **symbolsArr[ check % _31_ ];** since `symbolsArr.length = 32`

**Comment by chilts** [comment] 2016-10-05 23:39
Ah yes, I think you're right. Here's two runs of generating 1000 codes of `parts=1` and looking for the `Y` on the end:

```js
var cc = require('coupon-code')
for(var i = 0; i < 1000; i++ ) {
  console.log(cc.generate({ parts : 1 }))
}
```

The first version is with %31:

```
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
0
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
0
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
0
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
0
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
0
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
0
```

We never generate a "Y" for the check digit. And now with %32:

```
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
31
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
28
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
33
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
28
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
39
alderaan:~/src/chilts-node-coupon-code<master>$ node t.js | egrep 'Y$' | wc -l
40
```

So, the good news is, in the current version, both generate and validate call `checkDigitAlg1` and the two algorithms cancel each other out, thereby making sure the codes are valid.

The bad news is, if I change it, it's backwards incompatible therefore rendering all codes out there invalid. I would bump a "major" version number if I fix this, BUT I'm not entirely sure it's worth the effort.

I'm going to loop @grantm in here, since I think https://github.com/grantm/Algorithm-CouponCode is also subject to this and I'd be interested in his thoughts.

**Comment by chilts** [comment] 2016-10-05 23:40
Issue on the original Perl project opened here : https://github.com/grantm/Algorithm-CouponCode/issues/1

**Comment by grantm** [comment] 2016-10-06 04:40
This is not a bug, it's by design.  The algorithm for generating the check digit is a simple hash function that in this case takes three characters of input and produces one character of output that is reproducible, but looks kind of random(ish).

One very simple implementation would have been to sum the numeric index (0 .. 31) of the three characters and then apply modulo 32 to select a character for output. However an obvious flaw with this algorithm is that if two characters in the input are transposed, then the same output will be produced. In fact using this simple implementation, for any three input characters all six possible orderings would produce the same checksum - which for our purposes would be completely useless.

One way to mix things up is to apply a multiplying factor to the accumulated total before adding in the value for the next character. This means that the effect any input character has on the output will depend on both it's index value **and** it's position in the input stream.

Another way to mix things up is to avoid using modulo 32 since that will effectively disregard all but the 5 least significant bits of the accumulated value when translating back into the symbol space.

The other part of the algorithm I skipped over is that we want to produce a different check digit if the same initial three characters are entered in a different section of the input.  This is achieved by initialising the accumulator with the number of the section that the character belong to.

So to recap, the function has an initialiser, a multiplier and a final divisor for the modulo.  Both the multiplier and the multiplier are prime numbers and 31 is the largest prime number that fits in the symbol space.

I wouldn't want to give the impression that I applied computer science super powers to come up with this scheme - a lot of trial and error was involved. I tried a number of different algorithms including cryptographic hash functions and variations of the function described above with different multiplier and divisor values. I fed different inputs into each algorithm and recorded statistics for how often transposed input characters would produce the same checksum output character. I don't think it's possible to completely eliminate that type of error but I was able to select the hashing function that performed 'best' - i.e.: gave the lowest rate of transposition false positives. I was surprised to find that MD5 and SHA1 were among the worst performers by this metric.

Hope that explains things.

**Comment by chilts** [comment] 2016-10-06 08:58
You ... are ... awesome. :)

Well, that is a good explanation. I was sure when I implemented it that I figured you''d chosen 19 and 31 because they were prime, but I guess I didn't think about it too much after that.

Reading this, it did make me wonder if I had seeded the accumulator correctly with the part number, and it looks like I have. Thinking back, I'm sure I must have checked what I made against your version (I would have been very stupid if I didn't) but tbh, I can't actually remember (yes, I'm that stupid).

Perhaps I'll leave that as a task to myself to do in the future too, just to make sure it's all fine and dandy.

Anyway, that's for your in-depth explanation. @gtmsingh I hope the above explains it enough and I'll close this ticket as "it works as intended". :) Thanks for opening in the first place.

**Closed by chilts** 2016-10-06 08:58 UTC

**Comment by gtmsingh** [comment] 2018-03-16 09:59
Hi @grantm sorry for coming back to this after so long (it took a while to digest the techniques you tried out before coming up to this randomish code generation). Following important points I found from your explanation:
* Obvious flaw in just adding symbol's index to find out check digit
* Taking modulo 31 instead of 32 (really great thought!)

But I still feel that not including a symbol for the sake of improving our algo is not justifiable. I want to discuss more on the thought that - Having 32 symbols is the problem; instead if we have 31 characters we would:
1. Have all the characters taking part in coupon code generation
2. Disadvantage of using modulo 32 is also mitigated.

Let me know if this looks better, I might have some suggestion for relevant changes we can discuss.

**Comment by grantm** [comment] 2018-03-17 05:41
I am failing to understand what problem it is you're trying to solve.

**Comment by gtmsingh** [comment] 2018-03-17 06:40
Sorry, for not being specific last time! 
I am trying to find out if there can be some other way to optimize the randomness of check digit without loosing out on one VALID symbol available to the users.

**Comment by chilts** [comment] 2018-03-17 09:51
I think @grantm explanation about why it is %31 is satisfactory and if you try and use all 32 chars there, then all of the properties of the check-digit don't hold.

I was going to close the issue, but I realised that it is already closed.

Just to note, this isn't a bug and it'll never get changed in coupon-code. I'm going to lock this issue.
